# Describes the format for available services for KEBA charging staitons

request_data:
  name: Request data
  description: >
    Request new data from the charging station.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba

start:
  name: Authorize charging process
  description: >
    Authorizes a charging process with the given RFID tag.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    rfid:
      name: RFID tag
      description: RFID tag to be used (need to be configured within the charging station first)
      selector:
        text:
    rfid_class:
      name: RFID class (optional)
      description: RFID class to be used (RFID color code)
      selector:
        text:

stop:
  name: Deauthorize charging process
  description: >
    Deauthorizes the running charging process with the given RFID tag.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    rfid:
      name: RFID tag
      description: RFID tag to be used (need to be configured within the charging station first)
      selector:
        text:

set_energy:
  name: Set energy
  description: Sets the energy target after which the charging process stops.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    energy:
      name: Energy
      description: The energy target to stop charging. Setting 0 disables the limit.
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          unit_of_measurement: kWh

set_current:
  name: Set current
  description: Sets the maximum current for charging processes.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    current:
      name: Current
      description: >
        The maximum current used for the charging process.
        The value is limited by the DIP-switch settings and the used cable of the
        charging station.
      required: true
      default: 6
      selector:
        number:
          min: 6
          max: 63
          step: 1
          unit_of_measurement: A
    delay:
      name: Delay
      description: The delay in seconds after which the definded current should be set.
      default: 0
      selector:
        number:
          min: 0
          max: 860400
          step: 1
          unit_of_measurement: seconds

enable:
  name: Enable
  description: >
    Starts a charging process if charging station is authorized.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba

disable:
  name: Disable
  description: >
    Stops the charging process if charging station is authorized.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba

set_failsafe:
  name: Set failsafe
  description: >
    Set the failsafe mode of the charging station. If all parameters are 0, the failsafe mode will be disabled.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    failsafe_timeout:
      name: Failsafe timeout
      description: >
        Timeout after which the failsafe mode is triggered, if set_current was not executed during this time.
      default: 30
      selector:
        number:
          min: 1
          max: 3600
          step: 1
          unit_of_measurement: seconds
    failsafe_fallback:
      name: Failsafe fallback
      description: >
        Fallback current to be set after timeout.
      default: 6
      selector:
        number:
          min: 6
          max: 63
          step: 1
          unit_of_measurement: A
    failsafe_persist:
      name: Failsafe persist
      description: If failsafe_persist is False, the failsafe option is only used until charging station reboot. If failsafe_persist is True, the failsafe option will survive a reboot.
      default: False
      selector:
        boolean:

set_charging_power:
  name: Set charging power
  description: Set the charging power in kW if a charging operation is running. This service internally identifies the number of phases used for charging and sets the charging charging current to match the charging power as good as possible.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    power:
      name: Charging power
      description: Target charging power in kW
      required: true
      default: 11
      selector:
        number:
          min: 0
          max: 22
          step: 0.1
          unit_of_measurement: kW